language: node_js

# sudo: false
# before_install:
#   - add-apt-repository ppa:ubuntu-toolchain-r/test -y
#   - apt-get update -y
#   - apt-get install gcc-6 -y -q -f --no-install-recommends
#   - apt-get install g++-6 -y -q -f --no-install-recommends
#   - apt-get install build-essentials -y -q -f --no-install-recommends
#   - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

# addons:
#   apt:
#     sources:
#     - deadsnakes
#     - sourceline: 'ppa:ubuntu-toolchain-r/test'
#     - sourceline: 'deb https://packagecloud.io/chef/stable/ubuntu/precise main'
#       key_url: 'https://packagecloud.io/gpg.key'
#     packages:
#     - gcc-6
#     - g++-6

# services:
#   - mongodb
  
# env:
#   - CXX=g++-6