base:
  port: 80

paths:
  clientSrc: 'client'
  appFilesPaths: 
    - 'app.js' 
    - 'db.js'
    - 'boot.js'
    - 'setup.js'
    - 'utils/**/*.js'
    - 'routes/**/*.js'
    - 'models/**/*.js'
    - 'middlewares/**/*.js'
  clientDist: 'wwwroot/dist'
  appDist: 'wwwroot'
  testsSrc: 'tests/**/*.spec.js'
  webpackFile: 'webpack.config.js'
  indexPath: 'wwwroot/dist/index.html'

database:
  host: 'mongodb://test:test@ds048279.mlab.com:48279/event_man'
  creds:
    user: 'test'
    password: 'test'
